services:
  redis-sira:
    image: redis:7-alpine
    container_name: redis-sira
    restart: unless-stopped
    command: ["redis-server","--appendonly","yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 12

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:6333/readyz"]
      interval: 10s
      timeout: 5s
      retries: 12

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=Europe/Zurich
    volumes:
      - ./n8n_data:/home/node/.n8n
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:5678/healthz"]
      interval: 10s
      timeout: 5s
      retries: 12

  siranet:
    image: siranet:dev
    container_name: siranet
    restart: unless-stopped
    ports:
      - "8787:8081"
    environment:
      - REDIS_URL=redis://redis-sira:6379
      - QDRANT_URL=http://qdrant:6333
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost:8081/healthz"]
      interval: 10s
      timeout: 5s
      retries: 12

networks:
  default:
    name: sira_local_net
